[tools]
node = "23"
python = "3.13.2"
pnpm = "latest"
uv = "latest"
poetry = "latest"
java = "openjdk-25"
gradle = "latest"
go = "latest"
maven = "3.9"

[settings]
python.uv_venv_auto = true
experimental = true
