return {
  -- {
  --   "nvim-java/nvim-java",
  --   config = false,
  --   dependencies = {
  --     {
  --       "neovim/nvim-lspconfig",
  --       opts = {
  --         servers = {
  --           jdtls = {
  --             -- Your custom jdtls settings goes here
  --           },
  --         },
  --         setup = {
  --           jdtls = function()
  --             require("java").setup({
  --               jdk = {
  --                 auto_install = false,
  --               },
  --               root_markers = {
  --                 "settings.gradle",
  --                 "settings.gradle.kts",
  --                 "pom.xml",
  --                 "build.gradle",
  --                 "mvnw",
  --                 "gradlew",
  --                 "build.gradle",
  --                 "build.gradle.kts",
  --               },
  --             })
  --           end,
  --         },
  --       },
  --     },
  --   },
  -- },
}
